// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: bettery/funds/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "bettery.funds.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgMintToken defines the MsgMintToken message. */
export interface MsgMintToken {
  creator: string;
  receiver: string;
}

/** MsgMintTokenResponse defines the MsgMintTokenResponse message. */
export interface MsgMintTokenResponse {
  status: string;
}

export interface MintEvent {
  creator: string;
  receiver: string;
  amount: string;
  token: string;
  time: number;
}

/** MsgMintFromEvm defines the MsgMintFromEvm message. */
export interface MsgMintFromEvm {
  creator: string;
  evmChainId: number;
  evmBridge: string;
  evmToken: string;
  evmSender: string;
  cosmosReceiver: string;
  amount: string;
  nonce: number;
  txHash: string;
}

/** MsgMintFromEvmResponse defines the MsgMintFromEvmResponse message. */
export interface MsgMintFromEvmResponse {
}

/** MsgBurnToEvm defines the MsgBurnToEvm message. */
export interface MsgBurnToEvm {
  creator: string;
  evmChainId: number;
  evmBridge: string;
  evmToken: string;
  evmRecipient: string;
  amount: string;
}

/** MsgBurnToEvmResponse defines the MsgBurnToEvmResponse message. */
export interface MsgBurnToEvmResponse {
}

/** MsgSetCompanyPercent defines the MsgSetCompanyPercent message. */
export interface MsgSetCompanyPercent {
  creator: string;
  percent: number;
}

/** MsgSetCompanyPercentResponse defines the MsgSetCompanyPercentResponse message. */
export interface MsgSetCompanyPercentResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgMintToken(): MsgMintToken {
  return { creator: "", receiver: "" };
}

export const MsgMintToken: MessageFns<MsgMintToken> = {
  encode(message: MsgMintToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.receiver !== "") {
      writer.uint32(18).string(message.receiver);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.receiver = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintToken {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      receiver: isSet(object.receiver) ? globalThis.String(object.receiver) : "",
    };
  },

  toJSON(message: MsgMintToken): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.receiver !== "") {
      obj.receiver = message.receiver;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintToken>, I>>(base?: I): MsgMintToken {
    return MsgMintToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintToken>, I>>(object: I): MsgMintToken {
    const message = createBaseMsgMintToken();
    message.creator = object.creator ?? "";
    message.receiver = object.receiver ?? "";
    return message;
  },
};

function createBaseMsgMintTokenResponse(): MsgMintTokenResponse {
  return { status: "" };
}

export const MsgMintTokenResponse: MessageFns<MsgMintTokenResponse> = {
  encode(message: MsgMintTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintTokenResponse {
    return { status: isSet(object.status) ? globalThis.String(object.status) : "" };
  },

  toJSON(message: MsgMintTokenResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintTokenResponse>, I>>(base?: I): MsgMintTokenResponse {
    return MsgMintTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintTokenResponse>, I>>(object: I): MsgMintTokenResponse {
    const message = createBaseMsgMintTokenResponse();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseMintEvent(): MintEvent {
  return { creator: "", receiver: "", amount: "", token: "", time: 0 };
}

export const MintEvent: MessageFns<MintEvent> = {
  encode(message: MintEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.receiver !== "") {
      writer.uint32(18).string(message.receiver);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    if (message.time !== 0) {
      writer.uint32(40).uint64(message.time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MintEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMintEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.receiver = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.time = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MintEvent {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      receiver: isSet(object.receiver) ? globalThis.String(object.receiver) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
    };
  },

  toJSON(message: MintEvent): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.receiver !== "") {
      obj.receiver = message.receiver;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MintEvent>, I>>(base?: I): MintEvent {
    return MintEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MintEvent>, I>>(object: I): MintEvent {
    const message = createBaseMintEvent();
    message.creator = object.creator ?? "";
    message.receiver = object.receiver ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? "";
    message.time = object.time ?? 0;
    return message;
  },
};

function createBaseMsgMintFromEvm(): MsgMintFromEvm {
  return {
    creator: "",
    evmChainId: 0,
    evmBridge: "",
    evmToken: "",
    evmSender: "",
    cosmosReceiver: "",
    amount: "",
    nonce: 0,
    txHash: "",
  };
}

export const MsgMintFromEvm: MessageFns<MsgMintFromEvm> = {
  encode(message: MsgMintFromEvm, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.evmChainId !== 0) {
      writer.uint32(16).uint64(message.evmChainId);
    }
    if (message.evmBridge !== "") {
      writer.uint32(26).string(message.evmBridge);
    }
    if (message.evmToken !== "") {
      writer.uint32(34).string(message.evmToken);
    }
    if (message.evmSender !== "") {
      writer.uint32(42).string(message.evmSender);
    }
    if (message.cosmosReceiver !== "") {
      writer.uint32(50).string(message.cosmosReceiver);
    }
    if (message.amount !== "") {
      writer.uint32(58).string(message.amount);
    }
    if (message.nonce !== 0) {
      writer.uint32(64).uint64(message.nonce);
    }
    if (message.txHash !== "") {
      writer.uint32(74).string(message.txHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintFromEvm {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintFromEvm();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.evmChainId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.evmBridge = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.evmToken = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.evmSender = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cosmosReceiver = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.nonce = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintFromEvm {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      evmChainId: isSet(object.evmChainId)
        ? globalThis.Number(object.evmChainId)
        : isSet(object.evm_chain_id)
        ? globalThis.Number(object.evm_chain_id)
        : 0,
      evmBridge: isSet(object.evmBridge)
        ? globalThis.String(object.evmBridge)
        : isSet(object.evm_bridge)
        ? globalThis.String(object.evm_bridge)
        : "",
      evmToken: isSet(object.evmToken)
        ? globalThis.String(object.evmToken)
        : isSet(object.evm_token)
        ? globalThis.String(object.evm_token)
        : "",
      evmSender: isSet(object.evmSender)
        ? globalThis.String(object.evmSender)
        : isSet(object.evm_sender)
        ? globalThis.String(object.evm_sender)
        : "",
      cosmosReceiver: isSet(object.cosmosReceiver)
        ? globalThis.String(object.cosmosReceiver)
        : isSet(object.cosmos_receiver)
        ? globalThis.String(object.cosmos_receiver)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      nonce: isSet(object.nonce) ? globalThis.Number(object.nonce) : 0,
      txHash: isSet(object.txHash)
        ? globalThis.String(object.txHash)
        : isSet(object.tx_hash)
        ? globalThis.String(object.tx_hash)
        : "",
    };
  },

  toJSON(message: MsgMintFromEvm): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.evmChainId !== 0) {
      obj.evmChainId = Math.round(message.evmChainId);
    }
    if (message.evmBridge !== "") {
      obj.evmBridge = message.evmBridge;
    }
    if (message.evmToken !== "") {
      obj.evmToken = message.evmToken;
    }
    if (message.evmSender !== "") {
      obj.evmSender = message.evmSender;
    }
    if (message.cosmosReceiver !== "") {
      obj.cosmosReceiver = message.cosmosReceiver;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.nonce !== 0) {
      obj.nonce = Math.round(message.nonce);
    }
    if (message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintFromEvm>, I>>(base?: I): MsgMintFromEvm {
    return MsgMintFromEvm.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintFromEvm>, I>>(object: I): MsgMintFromEvm {
    const message = createBaseMsgMintFromEvm();
    message.creator = object.creator ?? "";
    message.evmChainId = object.evmChainId ?? 0;
    message.evmBridge = object.evmBridge ?? "";
    message.evmToken = object.evmToken ?? "";
    message.evmSender = object.evmSender ?? "";
    message.cosmosReceiver = object.cosmosReceiver ?? "";
    message.amount = object.amount ?? "";
    message.nonce = object.nonce ?? 0;
    message.txHash = object.txHash ?? "";
    return message;
  },
};

function createBaseMsgMintFromEvmResponse(): MsgMintFromEvmResponse {
  return {};
}

export const MsgMintFromEvmResponse: MessageFns<MsgMintFromEvmResponse> = {
  encode(_: MsgMintFromEvmResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintFromEvmResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintFromEvmResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgMintFromEvmResponse {
    return {};
  },

  toJSON(_: MsgMintFromEvmResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintFromEvmResponse>, I>>(base?: I): MsgMintFromEvmResponse {
    return MsgMintFromEvmResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintFromEvmResponse>, I>>(_: I): MsgMintFromEvmResponse {
    const message = createBaseMsgMintFromEvmResponse();
    return message;
  },
};

function createBaseMsgBurnToEvm(): MsgBurnToEvm {
  return { creator: "", evmChainId: 0, evmBridge: "", evmToken: "", evmRecipient: "", amount: "" };
}

export const MsgBurnToEvm: MessageFns<MsgBurnToEvm> = {
  encode(message: MsgBurnToEvm, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.evmChainId !== 0) {
      writer.uint32(16).uint64(message.evmChainId);
    }
    if (message.evmBridge !== "") {
      writer.uint32(26).string(message.evmBridge);
    }
    if (message.evmToken !== "") {
      writer.uint32(34).string(message.evmToken);
    }
    if (message.evmRecipient !== "") {
      writer.uint32(42).string(message.evmRecipient);
    }
    if (message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBurnToEvm {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBurnToEvm();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.evmChainId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.evmBridge = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.evmToken = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.evmRecipient = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgBurnToEvm {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      evmChainId: isSet(object.evmChainId)
        ? globalThis.Number(object.evmChainId)
        : isSet(object.evm_chain_id)
        ? globalThis.Number(object.evm_chain_id)
        : 0,
      evmBridge: isSet(object.evmBridge)
        ? globalThis.String(object.evmBridge)
        : isSet(object.evm_bridge)
        ? globalThis.String(object.evm_bridge)
        : "",
      evmToken: isSet(object.evmToken)
        ? globalThis.String(object.evmToken)
        : isSet(object.evm_token)
        ? globalThis.String(object.evm_token)
        : "",
      evmRecipient: isSet(object.evmRecipient)
        ? globalThis.String(object.evmRecipient)
        : isSet(object.evm_recipient)
        ? globalThis.String(object.evm_recipient)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
    };
  },

  toJSON(message: MsgBurnToEvm): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.evmChainId !== 0) {
      obj.evmChainId = Math.round(message.evmChainId);
    }
    if (message.evmBridge !== "") {
      obj.evmBridge = message.evmBridge;
    }
    if (message.evmToken !== "") {
      obj.evmToken = message.evmToken;
    }
    if (message.evmRecipient !== "") {
      obj.evmRecipient = message.evmRecipient;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBurnToEvm>, I>>(base?: I): MsgBurnToEvm {
    return MsgBurnToEvm.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBurnToEvm>, I>>(object: I): MsgBurnToEvm {
    const message = createBaseMsgBurnToEvm();
    message.creator = object.creator ?? "";
    message.evmChainId = object.evmChainId ?? 0;
    message.evmBridge = object.evmBridge ?? "";
    message.evmToken = object.evmToken ?? "";
    message.evmRecipient = object.evmRecipient ?? "";
    message.amount = object.amount ?? "";
    return message;
  },
};

function createBaseMsgBurnToEvmResponse(): MsgBurnToEvmResponse {
  return {};
}

export const MsgBurnToEvmResponse: MessageFns<MsgBurnToEvmResponse> = {
  encode(_: MsgBurnToEvmResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBurnToEvmResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBurnToEvmResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgBurnToEvmResponse {
    return {};
  },

  toJSON(_: MsgBurnToEvmResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBurnToEvmResponse>, I>>(base?: I): MsgBurnToEvmResponse {
    return MsgBurnToEvmResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBurnToEvmResponse>, I>>(_: I): MsgBurnToEvmResponse {
    const message = createBaseMsgBurnToEvmResponse();
    return message;
  },
};

function createBaseMsgSetCompanyPercent(): MsgSetCompanyPercent {
  return { creator: "", percent: 0 };
}

export const MsgSetCompanyPercent: MessageFns<MsgSetCompanyPercent> = {
  encode(message: MsgSetCompanyPercent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.percent !== 0) {
      writer.uint32(16).uint64(message.percent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCompanyPercent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetCompanyPercent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.percent = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetCompanyPercent {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      percent: isSet(object.percent) ? globalThis.Number(object.percent) : 0,
    };
  },

  toJSON(message: MsgSetCompanyPercent): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.percent !== 0) {
      obj.percent = Math.round(message.percent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCompanyPercent>, I>>(base?: I): MsgSetCompanyPercent {
    return MsgSetCompanyPercent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCompanyPercent>, I>>(object: I): MsgSetCompanyPercent {
    const message = createBaseMsgSetCompanyPercent();
    message.creator = object.creator ?? "";
    message.percent = object.percent ?? 0;
    return message;
  },
};

function createBaseMsgSetCompanyPercentResponse(): MsgSetCompanyPercentResponse {
  return {};
}

export const MsgSetCompanyPercentResponse: MessageFns<MsgSetCompanyPercentResponse> = {
  encode(_: MsgSetCompanyPercentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCompanyPercentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetCompanyPercentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetCompanyPercentResponse {
    return {};
  },

  toJSON(_: MsgSetCompanyPercentResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCompanyPercentResponse>, I>>(base?: I): MsgSetCompanyPercentResponse {
    return MsgSetCompanyPercentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCompanyPercentResponse>, I>>(_: I): MsgSetCompanyPercentResponse {
    const message = createBaseMsgSetCompanyPercentResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** MintToken defines the MintToken RPC. */
  MintToken(request: MsgMintToken): Promise<MsgMintTokenResponse>;
  /** MintFromEvm defines the MintFromEvm RPC. */
  MintFromEvm(request: MsgMintFromEvm): Promise<MsgMintFromEvmResponse>;
  /** BurnToEvm defines the BurnToEvm RPC. */
  BurnToEvm(request: MsgBurnToEvm): Promise<MsgBurnToEvmResponse>;
  /** SetCompanyPercent defines the SetCompanyPercent RPC. */
  SetCompanyPercent(request: MsgSetCompanyPercent): Promise<MsgSetCompanyPercentResponse>;
}

export const MsgServiceName = "bettery.funds.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.MintToken = this.MintToken.bind(this);
    this.MintFromEvm = this.MintFromEvm.bind(this);
    this.BurnToEvm = this.BurnToEvm.bind(this);
    this.SetCompanyPercent = this.SetCompanyPercent.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  MintToken(request: MsgMintToken): Promise<MsgMintTokenResponse> {
    const data = MsgMintToken.encode(request).finish();
    const promise = this.rpc.request(this.service, "MintToken", data);
    return promise.then((data) => MsgMintTokenResponse.decode(new BinaryReader(data)));
  }

  MintFromEvm(request: MsgMintFromEvm): Promise<MsgMintFromEvmResponse> {
    const data = MsgMintFromEvm.encode(request).finish();
    const promise = this.rpc.request(this.service, "MintFromEvm", data);
    return promise.then((data) => MsgMintFromEvmResponse.decode(new BinaryReader(data)));
  }

  BurnToEvm(request: MsgBurnToEvm): Promise<MsgBurnToEvmResponse> {
    const data = MsgBurnToEvm.encode(request).finish();
    const promise = this.rpc.request(this.service, "BurnToEvm", data);
    return promise.then((data) => MsgBurnToEvmResponse.decode(new BinaryReader(data)));
  }

  SetCompanyPercent(request: MsgSetCompanyPercent): Promise<MsgSetCompanyPercentResponse> {
    const data = MsgSetCompanyPercent.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetCompanyPercent", data);
    return promise.then((data) => MsgSetCompanyPercentResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
