// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/funds/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long from "long";
import { Params } from "./params";

export const protobufPackage = "bettery.funds.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params?: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgMintToken defines the MsgMintToken message. */
export interface MsgMintToken {
  creator: string;
}

/** MsgMintTokenResponse defines the MsgMintTokenResponse message. */
export interface MsgMintTokenResponse {
  status: string;
}

export interface MintEvent {
  creator: string;
  amount: string;
  token: string;
  time: Long;
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgMintToken(): MsgMintToken {
  return { creator: "" };
}

export const MsgMintToken: MessageFns<MsgMintToken> = {
  encode(message: MsgMintToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgMintToken>, I>>(base?: I): MsgMintToken {
    return MsgMintToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintToken>, I>>(object: I): MsgMintToken {
    const message = createBaseMsgMintToken();
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgMintTokenResponse(): MsgMintTokenResponse {
  return { status: "" };
}

export const MsgMintTokenResponse: MessageFns<MsgMintTokenResponse> = {
  encode(message: MsgMintTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgMintTokenResponse>, I>>(base?: I): MsgMintTokenResponse {
    return MsgMintTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintTokenResponse>, I>>(object: I): MsgMintTokenResponse {
    const message = createBaseMsgMintTokenResponse();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseMintEvent(): MintEvent {
  return { creator: "", amount: "", token: "", time: Long.UZERO };
}

export const MintEvent: MessageFns<MintEvent> = {
  encode(message: MintEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    if (!message.time.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.time.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MintEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMintEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.time = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MintEvent>, I>>(base?: I): MintEvent {
    return MintEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MintEvent>, I>>(object: I): MintEvent {
    const message = createBaseMintEvent();
    message.creator = object.creator ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? "";
    message.time = (object.time !== undefined && object.time !== null) ? Long.fromValue(object.time) : Long.UZERO;
    return message;
  },
};

/** Msg defines the Msg service. */
export type MsgService = typeof MsgService;
export const MsgService = {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams: {
    path: "/bettery.funds.v1.Msg/UpdateParams",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgUpdateParams): Buffer => Buffer.from(MsgUpdateParams.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgUpdateParams => MsgUpdateParams.decode(value),
    responseSerialize: (value: MsgUpdateParamsResponse): Buffer =>
      Buffer.from(MsgUpdateParamsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgUpdateParamsResponse => MsgUpdateParamsResponse.decode(value),
  },
  /** MintToken defines the MintToken RPC. */
  mintToken: {
    path: "/bettery.funds.v1.Msg/MintToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgMintToken): Buffer => Buffer.from(MsgMintToken.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgMintToken => MsgMintToken.decode(value),
    responseSerialize: (value: MsgMintTokenResponse): Buffer =>
      Buffer.from(MsgMintTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgMintTokenResponse => MsgMintTokenResponse.decode(value),
  },
} as const;

export interface MsgServer extends UntypedServiceImplementation {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams: handleUnaryCall<MsgUpdateParams, MsgUpdateParamsResponse>;
  /** MintToken defines the MintToken RPC. */
  mintToken: handleUnaryCall<MsgMintToken, MsgMintTokenResponse>;
}

export interface MsgClient extends Client {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams(
    request: MsgUpdateParams,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  updateParams(
    request: MsgUpdateParams,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  updateParams(
    request: MsgUpdateParams,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  /** MintToken defines the MintToken RPC. */
  mintToken(
    request: MsgMintToken,
    callback: (error: ServiceError | null, response: MsgMintTokenResponse) => void,
  ): ClientUnaryCall;
  mintToken(
    request: MsgMintToken,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgMintTokenResponse) => void,
  ): ClientUnaryCall;
  mintToken(
    request: MsgMintToken,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgMintTokenResponse) => void,
  ): ClientUnaryCall;
}

export const MsgClient = makeGenericClientConstructor(MsgService, "bettery.funds.v1.Msg") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MsgClient;
  service: typeof MsgService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
