// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/events/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "bettery.events.v1";

/** Events defines the Events message. */
export interface Events {
  id: number;
  creator: string;
  question: string;
  answers: string[];
  answersPool: number[];
  endTime: number;
  startTime: number;
  category: string;
  status: string;
  participants: string[];
  winningAnswer: string;
  answerSource: string;
}

function createBaseEvents(): Events {
  return {
    id: 0,
    creator: "",
    question: "",
    answers: [],
    answersPool: [],
    endTime: 0,
    startTime: 0,
    category: "",
    status: "",
    participants: [],
    winningAnswer: "",
    answerSource: "",
  };
}

export const Events: MessageFns<Events> = {
  encode(message: Events, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    if (message.question !== "") {
      writer.uint32(26).string(message.question);
    }
    for (const v of message.answers) {
      writer.uint32(34).string(v!);
    }
    writer.uint32(42).fork();
    for (const v of message.answersPool) {
      writer.uint64(v);
    }
    writer.join();
    if (message.endTime !== 0) {
      writer.uint32(48).uint64(message.endTime);
    }
    if (message.startTime !== 0) {
      writer.uint32(56).uint64(message.startTime);
    }
    if (message.category !== "") {
      writer.uint32(66).string(message.category);
    }
    if (message.status !== "") {
      writer.uint32(74).string(message.status);
    }
    for (const v of message.participants) {
      writer.uint32(82).string(v!);
    }
    if (message.winningAnswer !== "") {
      writer.uint32(90).string(message.winningAnswer);
    }
    if (message.answerSource !== "") {
      writer.uint32(98).string(message.answerSource);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Events {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvents();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answers.push(reader.string());
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.answersPool.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.answersPool.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.endTime = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.startTime = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.participants.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.winningAnswer = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.answerSource = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Events {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      answers: globalThis.Array.isArray(object?.answers) ? object.answers.map((e: any) => globalThis.String(e)) : [],
      answersPool: globalThis.Array.isArray(object?.answersPool)
        ? object.answersPool.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.answers_pool)
        ? object.answers_pool.map((e: any) => globalThis.Number(e))
        : [],
      endTime: isSet(object.endTime)
        ? globalThis.Number(object.endTime)
        : isSet(object.end_time)
        ? globalThis.Number(object.end_time)
        : 0,
      startTime: isSet(object.startTime)
        ? globalThis.Number(object.startTime)
        : isSet(object.start_time)
        ? globalThis.Number(object.start_time)
        : 0,
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      participants: globalThis.Array.isArray(object?.participants)
        ? object.participants.map((e: any) => globalThis.String(e))
        : [],
      winningAnswer: isSet(object.winningAnswer)
        ? globalThis.String(object.winningAnswer)
        : isSet(object.winning_answer)
        ? globalThis.String(object.winning_answer)
        : "",
      answerSource: isSet(object.answerSource)
        ? globalThis.String(object.answerSource)
        : isSet(object.answer_source)
        ? globalThis.String(object.answer_source)
        : "",
    };
  },

  toJSON(message: Events): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.answers?.length) {
      obj.answers = message.answers;
    }
    if (message.answersPool?.length) {
      obj.answersPool = message.answersPool.map((e) => Math.round(e));
    }
    if (message.endTime !== 0) {
      obj.endTime = Math.round(message.endTime);
    }
    if (message.startTime !== 0) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.participants?.length) {
      obj.participants = message.participants;
    }
    if (message.winningAnswer !== "") {
      obj.winningAnswer = message.winningAnswer;
    }
    if (message.answerSource !== "") {
      obj.answerSource = message.answerSource;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Events>, I>>(base?: I): Events {
    return Events.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Events>, I>>(object: I): Events {
    const message = createBaseEvents();
    message.id = object.id ?? 0;
    message.creator = object.creator ?? "";
    message.question = object.question ?? "";
    message.answers = object.answers?.map((e) => e) || [];
    message.answersPool = object.answersPool?.map((e) => e) || [];
    message.endTime = object.endTime ?? 0;
    message.startTime = object.startTime ?? 0;
    message.category = object.category ?? "";
    message.status = object.status ?? "";
    message.participants = object.participants?.map((e) => e) || [];
    message.winningAnswer = object.winningAnswer ?? "";
    message.answerSource = object.answerSource ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
