// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/events/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Events } from "./events";
import { Params } from "./params";
import { Participant } from "./participant";

export const protobufPackage = "bettery.events.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetEventsRequest defines the QueryGetEventsRequest message. */
export interface QueryGetEventsRequest {
  id: number;
}

/** QueryGetEventsResponse defines the QueryGetEventsResponse message. */
export interface QueryGetEventsResponse {
  events: Events | undefined;
}

/** QueryAllEventsRequest defines the QueryAllEventsRequest message. */
export interface QueryAllEventsRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllEventsResponse defines the QueryAllEventsResponse message. */
export interface QueryAllEventsResponse {
  events: Events[];
  pagination: PageResponse | undefined;
}

/** QueryGetParticipantRequest defines the QueryGetParticipantRequest message. */
export interface QueryGetParticipantRequest {
  id: number;
}

/** QueryGetParticipantResponse defines the QueryGetParticipantResponse message. */
export interface QueryGetParticipantResponse {
  participant: Participant | undefined;
}

/** QueryAllParticipantRequest defines the QueryAllParticipantRequest message. */
export interface QueryAllParticipantRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllParticipantResponse defines the QueryAllParticipantResponse message. */
export interface QueryAllParticipantResponse {
  participant: Participant[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetEventsRequest(): QueryGetEventsRequest {
  return { id: 0 };
}

export const QueryGetEventsRequest: MessageFns<QueryGetEventsRequest> = {
  encode(message: QueryGetEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEventsRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetEventsRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEventsRequest>, I>>(base?: I): QueryGetEventsRequest {
    return QueryGetEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEventsRequest>, I>>(object: I): QueryGetEventsRequest {
    const message = createBaseQueryGetEventsRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetEventsResponse(): QueryGetEventsResponse {
  return { events: undefined };
}

export const QueryGetEventsResponse: MessageFns<QueryGetEventsResponse> = {
  encode(message: QueryGetEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.events !== undefined) {
      Events.encode(message.events, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.events = Events.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEventsResponse {
    return { events: isSet(object.events) ? Events.fromJSON(object.events) : undefined };
  },

  toJSON(message: QueryGetEventsResponse): unknown {
    const obj: any = {};
    if (message.events !== undefined) {
      obj.events = Events.toJSON(message.events);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEventsResponse>, I>>(base?: I): QueryGetEventsResponse {
    return QueryGetEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEventsResponse>, I>>(object: I): QueryGetEventsResponse {
    const message = createBaseQueryGetEventsResponse();
    message.events = (object.events !== undefined && object.events !== null)
      ? Events.fromPartial(object.events)
      : undefined;
    return message;
  },
};

function createBaseQueryAllEventsRequest(): QueryAllEventsRequest {
  return { pagination: undefined };
}

export const QueryAllEventsRequest: MessageFns<QueryAllEventsRequest> = {
  encode(message: QueryAllEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllEventsRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllEventsRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllEventsRequest>, I>>(base?: I): QueryAllEventsRequest {
    return QueryAllEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllEventsRequest>, I>>(object: I): QueryAllEventsRequest {
    const message = createBaseQueryAllEventsRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllEventsResponse(): QueryAllEventsResponse {
  return { events: [], pagination: undefined };
}

export const QueryAllEventsResponse: MessageFns<QueryAllEventsResponse> = {
  encode(message: QueryAllEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.events) {
      Events.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.events.push(Events.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllEventsResponse {
    return {
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => Events.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllEventsResponse): unknown {
    const obj: any = {};
    if (message.events?.length) {
      obj.events = message.events.map((e) => Events.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllEventsResponse>, I>>(base?: I): QueryAllEventsResponse {
    return QueryAllEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllEventsResponse>, I>>(object: I): QueryAllEventsResponse {
    const message = createBaseQueryAllEventsResponse();
    message.events = object.events?.map((e) => Events.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetParticipantRequest(): QueryGetParticipantRequest {
  return { id: 0 };
}

export const QueryGetParticipantRequest: MessageFns<QueryGetParticipantRequest> = {
  encode(message: QueryGetParticipantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetParticipantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetParticipantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetParticipantRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetParticipantRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetParticipantRequest>, I>>(base?: I): QueryGetParticipantRequest {
    return QueryGetParticipantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetParticipantRequest>, I>>(object: I): QueryGetParticipantRequest {
    const message = createBaseQueryGetParticipantRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetParticipantResponse(): QueryGetParticipantResponse {
  return { participant: undefined };
}

export const QueryGetParticipantResponse: MessageFns<QueryGetParticipantResponse> = {
  encode(message: QueryGetParticipantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.participant !== undefined) {
      Participant.encode(message.participant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetParticipantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetParticipantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.participant = Participant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetParticipantResponse {
    return { participant: isSet(object.participant) ? Participant.fromJSON(object.participant) : undefined };
  },

  toJSON(message: QueryGetParticipantResponse): unknown {
    const obj: any = {};
    if (message.participant !== undefined) {
      obj.participant = Participant.toJSON(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetParticipantResponse>, I>>(base?: I): QueryGetParticipantResponse {
    return QueryGetParticipantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetParticipantResponse>, I>>(object: I): QueryGetParticipantResponse {
    const message = createBaseQueryGetParticipantResponse();
    message.participant = (object.participant !== undefined && object.participant !== null)
      ? Participant.fromPartial(object.participant)
      : undefined;
    return message;
  },
};

function createBaseQueryAllParticipantRequest(): QueryAllParticipantRequest {
  return { pagination: undefined };
}

export const QueryAllParticipantRequest: MessageFns<QueryAllParticipantRequest> = {
  encode(message: QueryAllParticipantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllParticipantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllParticipantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllParticipantRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllParticipantRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllParticipantRequest>, I>>(base?: I): QueryAllParticipantRequest {
    return QueryAllParticipantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllParticipantRequest>, I>>(object: I): QueryAllParticipantRequest {
    const message = createBaseQueryAllParticipantRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllParticipantResponse(): QueryAllParticipantResponse {
  return { participant: [], pagination: undefined };
}

export const QueryAllParticipantResponse: MessageFns<QueryAllParticipantResponse> = {
  encode(message: QueryAllParticipantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.participant) {
      Participant.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllParticipantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllParticipantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.participant.push(Participant.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllParticipantResponse {
    return {
      participant: globalThis.Array.isArray(object?.participant)
        ? object.participant.map((e: any) => Participant.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllParticipantResponse): unknown {
    const obj: any = {};
    if (message.participant?.length) {
      obj.participant = message.participant.map((e) => Participant.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllParticipantResponse>, I>>(base?: I): QueryAllParticipantResponse {
    return QueryAllParticipantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllParticipantResponse>, I>>(object: I): QueryAllParticipantResponse {
    const message = createBaseQueryAllParticipantResponse();
    message.participant = object.participant?.map((e) => Participant.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ListEvents Queries a list of Events items. */
  GetEvents(request: QueryGetEventsRequest): Promise<QueryGetEventsResponse>;
  /** ListEvents defines the ListEvents RPC. */
  ListEvents(request: QueryAllEventsRequest): Promise<QueryAllEventsResponse>;
  /** ListParticipant Queries a list of Participant items. */
  GetParticipant(request: QueryGetParticipantRequest): Promise<QueryGetParticipantResponse>;
  /** ListParticipant defines the ListParticipant RPC. */
  ListParticipant(request: QueryAllParticipantRequest): Promise<QueryAllParticipantResponse>;
}

export const QueryServiceName = "bettery.events.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetEvents = this.GetEvents.bind(this);
    this.ListEvents = this.ListEvents.bind(this);
    this.GetParticipant = this.GetParticipant.bind(this);
    this.ListParticipant = this.ListParticipant.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetEvents(request: QueryGetEventsRequest): Promise<QueryGetEventsResponse> {
    const data = QueryGetEventsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetEvents", data);
    return promise.then((data) => QueryGetEventsResponse.decode(new BinaryReader(data)));
  }

  ListEvents(request: QueryAllEventsRequest): Promise<QueryAllEventsResponse> {
    const data = QueryAllEventsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListEvents", data);
    return promise.then((data) => QueryAllEventsResponse.decode(new BinaryReader(data)));
  }

  GetParticipant(request: QueryGetParticipantRequest): Promise<QueryGetParticipantResponse> {
    const data = QueryGetParticipantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetParticipant", data);
    return promise.then((data) => QueryGetParticipantResponse.decode(new BinaryReader(data)));
  }

  ListParticipant(request: QueryAllParticipantRequest): Promise<QueryAllParticipantResponse> {
    const data = QueryAllParticipantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListParticipant", data);
    return promise.then((data) => QueryAllParticipantResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
