// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/events/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long from "long";
import { Params } from "./params";

export const protobufPackage = "bettery.events.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params?: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreateEvent defines the MsgCreateEvent message. */
export interface MsgCreateEvent {
  creator: string;
  id: Long;
  question: string;
  answers: string[];
  startTime: Long;
  endTime: Long;
  category: string;
}

/** MsgCreateEventResponse defines the MsgCreateEventResponse message. */
export interface MsgCreateEventResponse {
  id: Long;
}

/** MsgCreatePartEvent defines the MsgCreatePartEvent message. */
export interface MsgCreatePartEvent {
  creator: string;
  id: Long;
  eventId: Long;
  answers: string;
  amount: string;
  answerIndex: Long;
  token: string;
}

/** MsgCreatePartEventResponse defines the MsgCreatePartEventResponse message. */
export interface MsgCreatePartEventResponse {
}

/** MsgValidateEvent defines the MsgValidateEvent message. */
export interface MsgValidateEvent {
  creator: string;
  id: Long;
  eventId: Long;
  answerIndex: Long;
  answers: string;
  source: string;
}

/** MsgValidateEventResponse defines the MsgValidateEventResponse message. */
export interface MsgValidateEventResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateEvent(): MsgCreateEvent {
  return {
    creator: "",
    id: Long.UZERO,
    question: "",
    answers: [],
    startTime: Long.UZERO,
    endTime: Long.UZERO,
    category: "",
  };
}

export const MsgCreateEvent: MessageFns<MsgCreateEvent> = {
  encode(message: MsgCreateEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.id.toString());
    }
    if (message.question !== "") {
      writer.uint32(26).string(message.question);
    }
    for (const v of message.answers) {
      writer.uint32(34).string(v!);
    }
    if (!message.startTime.equals(Long.UZERO)) {
      writer.uint32(40).uint64(message.startTime.toString());
    }
    if (!message.endTime.equals(Long.UZERO)) {
      writer.uint32(48).uint64(message.endTime.toString());
    }
    if (message.category !== "") {
      writer.uint32(58).string(message.category);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answers.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startTime = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.endTime = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.category = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgCreateEvent>, I>>(base?: I): MsgCreateEvent {
    return MsgCreateEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateEvent>, I>>(object: I): MsgCreateEvent {
    const message = createBaseMsgCreateEvent();
    message.creator = object.creator ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.question = object.question ?? "";
    message.answers = object.answers?.map((e) => e) || [];
    message.startTime = (object.startTime !== undefined && object.startTime !== null)
      ? Long.fromValue(object.startTime)
      : Long.UZERO;
    message.endTime = (object.endTime !== undefined && object.endTime !== null)
      ? Long.fromValue(object.endTime)
      : Long.UZERO;
    message.category = object.category ?? "";
    return message;
  },
};

function createBaseMsgCreateEventResponse(): MsgCreateEventResponse {
  return { id: Long.UZERO };
}

export const MsgCreateEventResponse: MessageFns<MsgCreateEventResponse> = {
  encode(message: MsgCreateEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgCreateEventResponse>, I>>(base?: I): MsgCreateEventResponse {
    return MsgCreateEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateEventResponse>, I>>(object: I): MsgCreateEventResponse {
    const message = createBaseMsgCreateEventResponse();
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseMsgCreatePartEvent(): MsgCreatePartEvent {
  return {
    creator: "",
    id: Long.UZERO,
    eventId: Long.UZERO,
    answers: "",
    amount: "",
    answerIndex: Long.UZERO,
    token: "",
  };
}

export const MsgCreatePartEvent: MessageFns<MsgCreatePartEvent> = {
  encode(message: MsgCreatePartEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.id.toString());
    }
    if (!message.eventId.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.eventId.toString());
    }
    if (message.answers !== "") {
      writer.uint32(34).string(message.answers);
    }
    if (message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (!message.answerIndex.equals(Long.UZERO)) {
      writer.uint32(48).uint64(message.answerIndex.toString());
    }
    if (message.token !== "") {
      writer.uint32(58).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePartEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePartEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eventId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answers = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.answerIndex = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgCreatePartEvent>, I>>(base?: I): MsgCreatePartEvent {
    return MsgCreatePartEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePartEvent>, I>>(object: I): MsgCreatePartEvent {
    const message = createBaseMsgCreatePartEvent();
    message.creator = object.creator ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.eventId = (object.eventId !== undefined && object.eventId !== null)
      ? Long.fromValue(object.eventId)
      : Long.UZERO;
    message.answers = object.answers ?? "";
    message.amount = object.amount ?? "";
    message.answerIndex = (object.answerIndex !== undefined && object.answerIndex !== null)
      ? Long.fromValue(object.answerIndex)
      : Long.UZERO;
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseMsgCreatePartEventResponse(): MsgCreatePartEventResponse {
  return {};
}

export const MsgCreatePartEventResponse: MessageFns<MsgCreatePartEventResponse> = {
  encode(_: MsgCreatePartEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePartEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePartEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgCreatePartEventResponse>, I>>(base?: I): MsgCreatePartEventResponse {
    return MsgCreatePartEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePartEventResponse>, I>>(_: I): MsgCreatePartEventResponse {
    const message = createBaseMsgCreatePartEventResponse();
    return message;
  },
};

function createBaseMsgValidateEvent(): MsgValidateEvent {
  return { creator: "", id: Long.UZERO, eventId: Long.UZERO, answerIndex: Long.UZERO, answers: "", source: "" };
}

export const MsgValidateEvent: MessageFns<MsgValidateEvent> = {
  encode(message: MsgValidateEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.id.toString());
    }
    if (!message.eventId.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.eventId.toString());
    }
    if (!message.answerIndex.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.answerIndex.toString());
    }
    if (message.answers !== "") {
      writer.uint32(42).string(message.answers);
    }
    if (message.source !== "") {
      writer.uint32(50).string(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eventId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.answerIndex = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.answers = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgValidateEvent>, I>>(base?: I): MsgValidateEvent {
    return MsgValidateEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateEvent>, I>>(object: I): MsgValidateEvent {
    const message = createBaseMsgValidateEvent();
    message.creator = object.creator ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.eventId = (object.eventId !== undefined && object.eventId !== null)
      ? Long.fromValue(object.eventId)
      : Long.UZERO;
    message.answerIndex = (object.answerIndex !== undefined && object.answerIndex !== null)
      ? Long.fromValue(object.answerIndex)
      : Long.UZERO;
    message.answers = object.answers ?? "";
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseMsgValidateEventResponse(): MsgValidateEventResponse {
  return {};
}

export const MsgValidateEventResponse: MessageFns<MsgValidateEventResponse> = {
  encode(_: MsgValidateEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MsgValidateEventResponse>, I>>(base?: I): MsgValidateEventResponse {
    return MsgValidateEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateEventResponse>, I>>(_: I): MsgValidateEventResponse {
    const message = createBaseMsgValidateEventResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export type MsgService = typeof MsgService;
export const MsgService = {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams: {
    path: "/bettery.events.v1.Msg/UpdateParams",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgUpdateParams): Buffer => Buffer.from(MsgUpdateParams.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgUpdateParams => MsgUpdateParams.decode(value),
    responseSerialize: (value: MsgUpdateParamsResponse): Buffer =>
      Buffer.from(MsgUpdateParamsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgUpdateParamsResponse => MsgUpdateParamsResponse.decode(value),
  },
  /** CreateEvent defines the CreateEvent RPC. */
  createEvent: {
    path: "/bettery.events.v1.Msg/CreateEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgCreateEvent): Buffer => Buffer.from(MsgCreateEvent.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgCreateEvent => MsgCreateEvent.decode(value),
    responseSerialize: (value: MsgCreateEventResponse): Buffer =>
      Buffer.from(MsgCreateEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgCreateEventResponse => MsgCreateEventResponse.decode(value),
  },
  /** CreatePartEvent defines the CreatePartEvent RPC. */
  createPartEvent: {
    path: "/bettery.events.v1.Msg/CreatePartEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgCreatePartEvent): Buffer => Buffer.from(MsgCreatePartEvent.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgCreatePartEvent => MsgCreatePartEvent.decode(value),
    responseSerialize: (value: MsgCreatePartEventResponse): Buffer =>
      Buffer.from(MsgCreatePartEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgCreatePartEventResponse => MsgCreatePartEventResponse.decode(value),
  },
  /** ValidateEvent defines the ValidateEvent RPC. */
  validateEvent: {
    path: "/bettery.events.v1.Msg/ValidateEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MsgValidateEvent): Buffer => Buffer.from(MsgValidateEvent.encode(value).finish()),
    requestDeserialize: (value: Buffer): MsgValidateEvent => MsgValidateEvent.decode(value),
    responseSerialize: (value: MsgValidateEventResponse): Buffer =>
      Buffer.from(MsgValidateEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MsgValidateEventResponse => MsgValidateEventResponse.decode(value),
  },
} as const;

export interface MsgServer extends UntypedServiceImplementation {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams: handleUnaryCall<MsgUpdateParams, MsgUpdateParamsResponse>;
  /** CreateEvent defines the CreateEvent RPC. */
  createEvent: handleUnaryCall<MsgCreateEvent, MsgCreateEventResponse>;
  /** CreatePartEvent defines the CreatePartEvent RPC. */
  createPartEvent: handleUnaryCall<MsgCreatePartEvent, MsgCreatePartEventResponse>;
  /** ValidateEvent defines the ValidateEvent RPC. */
  validateEvent: handleUnaryCall<MsgValidateEvent, MsgValidateEventResponse>;
}

export interface MsgClient extends Client {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  updateParams(
    request: MsgUpdateParams,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  updateParams(
    request: MsgUpdateParams,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  updateParams(
    request: MsgUpdateParams,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgUpdateParamsResponse) => void,
  ): ClientUnaryCall;
  /** CreateEvent defines the CreateEvent RPC. */
  createEvent(
    request: MsgCreateEvent,
    callback: (error: ServiceError | null, response: MsgCreateEventResponse) => void,
  ): ClientUnaryCall;
  createEvent(
    request: MsgCreateEvent,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgCreateEventResponse) => void,
  ): ClientUnaryCall;
  createEvent(
    request: MsgCreateEvent,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgCreateEventResponse) => void,
  ): ClientUnaryCall;
  /** CreatePartEvent defines the CreatePartEvent RPC. */
  createPartEvent(
    request: MsgCreatePartEvent,
    callback: (error: ServiceError | null, response: MsgCreatePartEventResponse) => void,
  ): ClientUnaryCall;
  createPartEvent(
    request: MsgCreatePartEvent,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgCreatePartEventResponse) => void,
  ): ClientUnaryCall;
  createPartEvent(
    request: MsgCreatePartEvent,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgCreatePartEventResponse) => void,
  ): ClientUnaryCall;
  /** ValidateEvent defines the ValidateEvent RPC. */
  validateEvent(
    request: MsgValidateEvent,
    callback: (error: ServiceError | null, response: MsgValidateEventResponse) => void,
  ): ClientUnaryCall;
  validateEvent(
    request: MsgValidateEvent,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MsgValidateEventResponse) => void,
  ): ClientUnaryCall;
  validateEvent(
    request: MsgValidateEvent,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MsgValidateEventResponse) => void,
  ): ClientUnaryCall;
}

export const MsgClient = makeGenericClientConstructor(MsgService, "bettery.events.v1.Msg") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MsgClient;
  service: typeof MsgService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
