// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/events/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "bettery.events.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreateEvent defines the MsgCreateEvent message. */
export interface MsgCreateEvent {
  creator: string;
  id: number;
  question: string;
  answers: string[];
  startTime: number;
  endTime: number;
  category: string;
}

/** MsgCreateEventResponse defines the MsgCreateEventResponse message. */
export interface MsgCreateEventResponse {
  id: number;
}

/** MsgCreatePartEvent defines the MsgCreatePartEvent message. */
export interface MsgCreatePartEvent {
  creator: string;
  id: number;
  eventId: number;
  answers: string;
  amount: string;
  answerIndex: number;
  token: string;
}

/** MsgCreatePartEventResponse defines the MsgCreatePartEventResponse message. */
export interface MsgCreatePartEventResponse {
}

/** MsgValidateEvent defines the MsgValidateEvent message. */
export interface MsgValidateEvent {
  creator: string;
  id: number;
  eventId: number;
  answerIndex: number;
  answers: string;
  source: string;
}

/** MsgValidateEventResponse defines the MsgValidateEventResponse message. */
export interface MsgValidateEventResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateEvent(): MsgCreateEvent {
  return { creator: "", id: 0, question: "", answers: [], startTime: 0, endTime: 0, category: "" };
}

export const MsgCreateEvent: MessageFns<MsgCreateEvent> = {
  encode(message: MsgCreateEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.question !== "") {
      writer.uint32(26).string(message.question);
    }
    for (const v of message.answers) {
      writer.uint32(34).string(v!);
    }
    if (message.startTime !== 0) {
      writer.uint32(40).uint64(message.startTime);
    }
    if (message.endTime !== 0) {
      writer.uint32(48).uint64(message.endTime);
    }
    if (message.category !== "") {
      writer.uint32(58).string(message.category);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answers.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startTime = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.endTime = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.category = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateEvent {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      answers: globalThis.Array.isArray(object?.answers) ? object.answers.map((e: any) => globalThis.String(e)) : [],
      startTime: isSet(object.startTime)
        ? globalThis.Number(object.startTime)
        : isSet(object.start_time)
        ? globalThis.Number(object.start_time)
        : 0,
      endTime: isSet(object.endTime)
        ? globalThis.Number(object.endTime)
        : isSet(object.end_time)
        ? globalThis.Number(object.end_time)
        : 0,
      category: isSet(object.category) ? globalThis.String(object.category) : "",
    };
  },

  toJSON(message: MsgCreateEvent): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.answers?.length) {
      obj.answers = message.answers;
    }
    if (message.startTime !== 0) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.endTime !== 0) {
      obj.endTime = Math.round(message.endTime);
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateEvent>, I>>(base?: I): MsgCreateEvent {
    return MsgCreateEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateEvent>, I>>(object: I): MsgCreateEvent {
    const message = createBaseMsgCreateEvent();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.question = object.question ?? "";
    message.answers = object.answers?.map((e) => e) || [];
    message.startTime = object.startTime ?? 0;
    message.endTime = object.endTime ?? 0;
    message.category = object.category ?? "";
    return message;
  },
};

function createBaseMsgCreateEventResponse(): MsgCreateEventResponse {
  return { id: 0 };
}

export const MsgCreateEventResponse: MessageFns<MsgCreateEventResponse> = {
  encode(message: MsgCreateEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateEventResponse {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: MsgCreateEventResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateEventResponse>, I>>(base?: I): MsgCreateEventResponse {
    return MsgCreateEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateEventResponse>, I>>(object: I): MsgCreateEventResponse {
    const message = createBaseMsgCreateEventResponse();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgCreatePartEvent(): MsgCreatePartEvent {
  return { creator: "", id: 0, eventId: 0, answers: "", amount: "", answerIndex: 0, token: "" };
}

export const MsgCreatePartEvent: MessageFns<MsgCreatePartEvent> = {
  encode(message: MsgCreatePartEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.eventId !== 0) {
      writer.uint32(24).uint64(message.eventId);
    }
    if (message.answers !== "") {
      writer.uint32(34).string(message.answers);
    }
    if (message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (message.answerIndex !== 0) {
      writer.uint32(48).uint64(message.answerIndex);
    }
    if (message.token !== "") {
      writer.uint32(58).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePartEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePartEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eventId = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.answers = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.answerIndex = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreatePartEvent {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      answers: isSet(object.answers) ? globalThis.String(object.answers) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      answerIndex: isSet(object.answerIndex)
        ? globalThis.Number(object.answerIndex)
        : isSet(object.answer_index)
        ? globalThis.Number(object.answer_index)
        : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: MsgCreatePartEvent): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.answers !== "") {
      obj.answers = message.answers;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.answerIndex !== 0) {
      obj.answerIndex = Math.round(message.answerIndex);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreatePartEvent>, I>>(base?: I): MsgCreatePartEvent {
    return MsgCreatePartEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePartEvent>, I>>(object: I): MsgCreatePartEvent {
    const message = createBaseMsgCreatePartEvent();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.eventId = object.eventId ?? 0;
    message.answers = object.answers ?? "";
    message.amount = object.amount ?? "";
    message.answerIndex = object.answerIndex ?? 0;
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseMsgCreatePartEventResponse(): MsgCreatePartEventResponse {
  return {};
}

export const MsgCreatePartEventResponse: MessageFns<MsgCreatePartEventResponse> = {
  encode(_: MsgCreatePartEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePartEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePartEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCreatePartEventResponse {
    return {};
  },

  toJSON(_: MsgCreatePartEventResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreatePartEventResponse>, I>>(base?: I): MsgCreatePartEventResponse {
    return MsgCreatePartEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePartEventResponse>, I>>(_: I): MsgCreatePartEventResponse {
    const message = createBaseMsgCreatePartEventResponse();
    return message;
  },
};

function createBaseMsgValidateEvent(): MsgValidateEvent {
  return { creator: "", id: 0, eventId: 0, answerIndex: 0, answers: "", source: "" };
}

export const MsgValidateEvent: MessageFns<MsgValidateEvent> = {
  encode(message: MsgValidateEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.eventId !== 0) {
      writer.uint32(24).uint64(message.eventId);
    }
    if (message.answerIndex !== 0) {
      writer.uint32(32).uint64(message.answerIndex);
    }
    if (message.answers !== "") {
      writer.uint32(42).string(message.answers);
    }
    if (message.source !== "") {
      writer.uint32(50).string(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eventId = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.answerIndex = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.answers = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgValidateEvent {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      answerIndex: isSet(object.answerIndex)
        ? globalThis.Number(object.answerIndex)
        : isSet(object.answer_index)
        ? globalThis.Number(object.answer_index)
        : 0,
      answers: isSet(object.answers) ? globalThis.String(object.answers) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
    };
  },

  toJSON(message: MsgValidateEvent): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.answerIndex !== 0) {
      obj.answerIndex = Math.round(message.answerIndex);
    }
    if (message.answers !== "") {
      obj.answers = message.answers;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgValidateEvent>, I>>(base?: I): MsgValidateEvent {
    return MsgValidateEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateEvent>, I>>(object: I): MsgValidateEvent {
    const message = createBaseMsgValidateEvent();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.eventId = object.eventId ?? 0;
    message.answerIndex = object.answerIndex ?? 0;
    message.answers = object.answers ?? "";
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseMsgValidateEventResponse(): MsgValidateEventResponse {
  return {};
}

export const MsgValidateEventResponse: MessageFns<MsgValidateEventResponse> = {
  encode(_: MsgValidateEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgValidateEventResponse {
    return {};
  },

  toJSON(_: MsgValidateEventResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgValidateEventResponse>, I>>(base?: I): MsgValidateEventResponse {
    return MsgValidateEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateEventResponse>, I>>(_: I): MsgValidateEventResponse {
    const message = createBaseMsgValidateEventResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** CreateEvent defines the CreateEvent RPC. */
  CreateEvent(request: MsgCreateEvent): Promise<MsgCreateEventResponse>;
  /** CreatePartEvent defines the CreatePartEvent RPC. */
  CreatePartEvent(request: MsgCreatePartEvent): Promise<MsgCreatePartEventResponse>;
  /** ValidateEvent defines the ValidateEvent RPC. */
  ValidateEvent(request: MsgValidateEvent): Promise<MsgValidateEventResponse>;
}

export const MsgServiceName = "bettery.events.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreateEvent = this.CreateEvent.bind(this);
    this.CreatePartEvent = this.CreatePartEvent.bind(this);
    this.ValidateEvent = this.ValidateEvent.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  CreateEvent(request: MsgCreateEvent): Promise<MsgCreateEventResponse> {
    const data = MsgCreateEvent.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateEvent", data);
    return promise.then((data) => MsgCreateEventResponse.decode(new BinaryReader(data)));
  }

  CreatePartEvent(request: MsgCreatePartEvent): Promise<MsgCreatePartEventResponse> {
    const data = MsgCreatePartEvent.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreatePartEvent", data);
    return promise.then((data) => MsgCreatePartEventResponse.decode(new BinaryReader(data)));
  }

  ValidateEvent(request: MsgValidateEvent): Promise<MsgValidateEventResponse> {
    const data = MsgValidateEvent.encode(request).finish();
    const promise = this.rpc.request(this.service, "ValidateEvent", data);
    return promise.then((data) => MsgValidateEventResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
