// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: bettery/events/v1/validator.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "bettery.events.v1";

/** Validator defines the Validator message. */
export interface Validator {
  id: number;
  eventId: number;
  answer: string;
  source: string;
  refunded: boolean;
  companyAmount: string;
  createdAt: number;
}

function createBaseValidator(): Validator {
  return { id: 0, eventId: 0, answer: "", source: "", refunded: false, companyAmount: "", createdAt: 0 };
}

export const Validator: MessageFns<Validator> = {
  encode(message: Validator, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.eventId !== 0) {
      writer.uint32(16).uint64(message.eventId);
    }
    if (message.answer !== "") {
      writer.uint32(26).string(message.answer);
    }
    if (message.source !== "") {
      writer.uint32(34).string(message.source);
    }
    if (message.refunded !== false) {
      writer.uint32(40).bool(message.refunded);
    }
    if (message.companyAmount !== "") {
      writer.uint32(50).string(message.companyAmount);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).uint64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Validator {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidator();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.eventId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.refunded = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.companyAmount = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Validator {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      eventId: isSet(object.eventId)
        ? globalThis.Number(object.eventId)
        : isSet(object.event_id)
        ? globalThis.Number(object.event_id)
        : 0,
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      refunded: isSet(object.refunded) ? globalThis.Boolean(object.refunded) : false,
      companyAmount: isSet(object.companyAmount)
        ? globalThis.String(object.companyAmount)
        : isSet(object.company_amount)
        ? globalThis.String(object.company_amount)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
    };
  },

  toJSON(message: Validator): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.eventId !== 0) {
      obj.eventId = Math.round(message.eventId);
    }
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.refunded !== false) {
      obj.refunded = message.refunded;
    }
    if (message.companyAmount !== "") {
      obj.companyAmount = message.companyAmount;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Validator>, I>>(base?: I): Validator {
    return Validator.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Validator>, I>>(object: I): Validator {
    const message = createBaseValidator();
    message.id = object.id ?? 0;
    message.eventId = object.eventId ?? 0;
    message.answer = object.answer ?? "";
    message.source = object.source ?? "";
    message.refunded = object.refunded ?? false;
    message.companyAmount = object.companyAmount ?? "";
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
